database:
  dialect: mysql      # postgres | mysql | sqlite3
  host: localhost
  port: 3306
  user: root
  password: 123456
  dbname: tsdd

  max_open_conns: 10
  max_idle_conns: 2
  conn_max_lifetime: 30m
  conn_max_idle_time: 10m

logging:
  level: info            # debug | info | warn | error
  format: json           # json | text
  add_source: true      # include source locations in logs